name: Secrets Detection
run-name: Secrets Detection ${{ github.sha }} by @${{ github.actor }}

on:
  merge_group:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@c1f2e912239240108482d79ea01ab25d90b27ac7 # v3.88.16
        with:
          extra_args: --only-verified
